baseURL = "https://guy.sh"
title = "Guy Bianco IV"

languageCode = "en-us"
defaultContentLanguage = "en"

theme = "hugo-coder"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
  author = "Guy Bianco IV"
  info = "developer, tinkerer, musician"
  description = "Guy Bianco IV's personal website"
  keywords = "blog,developer,personal"
  # avatarurl = "images/avatar.jpg"
  gravatar = "gjbiancoiv@gmail.com"

  colorscheme = "dark"
  hidecolorschemetoggle = false

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # footercontent = "Enter a text here."
  hideFooter = true
  hideCredits = false
  hideCopyright = false
  since = 2018

  # enableTwemoji = true

#   customCSS = ["css/custom.css"]
#   customSCSS = ["scss/custom.scss"]
#   customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/gjbianco/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/guy_bianco/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/gjbiancoiv/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
